spring:
#DataSource
  datasource:
  #数据库路径
    url: jdbc:sqlite:Database/SHDB.sqlite
    #数据库用户名
    username:
    #数据库用户名密码
    password:
    #数据库驱动
    driver-class-name: org.sqlite.JDBC
    sqlDatePattern: yyyy-MM-dd HH:mm:ss
#apk存放路径,自定义目录用于app的下载
  apkDir: /Users/gxy/workSpace/webProject/SPSS_SHServer/apks/
#static
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${spring.apkDir}

#webApp
server:
#服务器端口
  port: 8080
  #项目名
 #context-path: /***
  servlet:
#  HTTPS
#    测试
#    key-store: ssl/test_keystore.p12
#    key-store-password: 123456
#    key-alias: tomcat
#    key-store-type: PKCS12
#    enabled: true

#mqtt
mqtt:
  broker:
    port: 8883
    host: 0.0.0.0
    jmx: false
  consumer:
    host: vm://localhost
    timeout: 5000
    session-window-seconds: 300
    #topic格式
    topic-pattern: .* #topic模式
    topic-level: 5 #例：/t1 /t1/ /t1/t2/ /t1/t2/t3/ /t1/t2/t3/t4/

#Logging
logging:
  config: ./config/logback-spring.xml

#JWT
jwt:
    header: Authorization
    secret: mySecret
    tokenHead: "Bearer "
    #过期时间以天为单位
    expiration: 7

Swagger2:
  title: 上品上生智能家居resetful 接口文档
  version: 1.0

tencent:
#腾讯短信
    sms:
      appid:
      appkey:
      templateid:
      smsSign:
      interval:

